### ISSUE TITLE
Could you add support for washing, smoking, and blasting?

### ISSUE THREAD

**Issue by vizthex123** [jaredlll08/CreateTweaker#10]
I can't find it on the [CT Wiki](https://docs.blamejared.com/1.16/en/mods/Create/Compacting/), so I assume it's not in the mod? (Or the wiki isn't up-to-date)

**Comment by jaredlll08** [comment]
As far as I'm aware, this mod supports all recipe types that Create offers, which can be found here: https://github.com/Creators-of-Create/Create/blob/mc1.16/dev/src/main/java/com/simibubi/create/AllRecipeTypes.java#L37-L50

Smoking and Blasting use the smoker and blasting registry from vanilla.

Washing seems to be https://docs.blamejared.com/1.16/en/mods/Create/Splashing/

**Comment by vizthex123** [comment]
Yeah, I noticed they're mislabeled. Bit annoying.
