### ISSUE TITLE
not compatible with sequenced assembly in create 3.2

### ISSUE THREAD

**Issue by thiccmeme** [jaredlll08/CreateTweaker#11]
after attempting to create a script that functions using sequenced assembly as the chosen crafting method which was newly added in the latest create update at the time (create 3.2) it is not recognized. if the command for recipe type dumps is given in-game the recipe type (<recipetype:create:sequenced_assembly>) does appear, however, upon attempting to use it in a script it says it is not recognized. I can get other recipe types within create to function, such as mechanical crafting, however, this is no updated documentation released for create 3.2 and its addition of sequenced assembly; thus I have no way of knowing if this error is one of the user, simply not knowing how to input the recipe type properly because of a lack of documentation, or if it is the omission of sequenced assembly as a recognized recipe type within this mod.

please let me know if there is any way to fix this if it is simply user error, thank you

**Comment by Duorhs** [comment]
It seems that after the 0.3.2c update of create , some recipe type in script have issues.

**Comment by jaredlll08** [comment]
This was fixed in https://github.com/jaredlll08/CreateTweaker/commit/3e91fb166969a34b2cf2888773e6a07cdfbb26d8 and should be released by now
