### ISSUE TITLE
mechanical crafting adds the recipes to the crafting table and not the other way around

### ISSUE THREAD

**Issue by PandaBoy444** [jaredlll08/CreateTweaker#13]
When I add an item to the crafting table, the create mechanical crafter doesn't know about it so it doesn't add it to it's own recipes, but when I add an item to the crafter it always get's copied into the crafting table.

**Comment by jaredlll08** [comment]
There is nothing that I can do to fix it, it is on Create's side.
https://github.com/Creators-of-Create/Create/issues/1424
https://github.com/Creators-of-Create/Create/issues/1112

**Comment by PandaBoy444** [comment]
Oh ok, thank you

**Comment by jaredlll08** [comment]
https://github.com/Creators-of-Create/Create/pull/2788
