### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by DAmNRelentless** [jaredlll08/CreateTweaker#2]
On the CF project site, you just provided a link to the CraftTweaker documentation but no explicit page.
The documentation for CreateTweaker is not included in the CraftTweaker documentation yet, is it?

**Comment by DAmNRelentless** [comment]
I am dumb. It's just not there for my language. I thought if a page doesn't exist for your language, it would be displayed in english instead.

**Comment by felixgames097** [comment]
@DAmNRelentless can u give a link?

**Comment by DAmNRelentless** [comment]
> @DAmNRelentless can u give a link?

https://docs.blamejared.com/1.16/en/mods/Create/Compacting/

**Comment by jaredlll08** [comment]
I can look into adding an english version fallback if you think that would be a good idea?

**Comment by DAmNRelentless** [comment]
@jaredlll08 Would be very helpful indeed. It's kind of confusing that pages are missing if they are not localized and it was like that in 1.12 and I really liked it.
