### ISSUE TITLE
[minor update request] CreateTweaker incompatable wtih 0.3.2g

### ISSUE THREAD

**Issue by SteamDoge9000** [jaredlll08/CreateTweaker#21]
no major crash or anything, just the launcher wont start because its looking for 0.3.2f and it was today that it received an update for 0.3.2g

a quick update to curseforge to allow it to run with the new version would be nice

thanks in advance, -CreateTweaker user

**Comment by jaredlll08** [comment]
Fixed by 462c39fe1ab56aa5d3cc79fe300f14167059dbec

**Comment by SteamDoge9000** [comment]
thx gm8

**Comment by SteamDoge9000** [comment]
fi possable, could you try to push this up to curseforge?

**Comment by jaredlll08** [comment]
It was on curse a few minutes after I made the commit.
https://www.curseforge.com/minecraft/mc-mods/createtweaker

**Comment by SteamDoge9000** [comment]
apologies, curseforge app can be a bit behind sometimes
