### ISSUE TITLE
Simply Inquiring about 1.18.1 Update

### ISSUE THREAD

**Issue by Camawama** [jaredlll08/CreateTweaker#22]
You disabled the comment section on CurseForge so I couldn't ask there. Do you plan on updating to 1.18.1?

**Comment by jaredlll08** [comment]
Yep update is done, just waiting on something else to be fixed before it can be released.

**Comment by Camawama** [comment]
Awesome! Thank you :)

**Comment by jaredlll08** [comment]
Done https://github.com/jaredlll08/CreateTweaker/commit/09445356925419c0111b0553a70f272a601f8bd5
