### ISSUE TITLE
.reuse() doesn't work on mechanical crafter recipes

### ISSUE THREAD

**Issue by etherealgears** [jaredlll08/CreateTweaker#23]
This is for version 1.16.5-7.1.2.508. When making custom mechanical crafter recipes, appending .reuse() after an item doesn't stop it from being consumed in the crafting process. Since this works for regular crafting table recipes with CraftTweaker, I was assuming it would work for the mechanical crafters as well, but maybe this is deliberate?

**Comment by jaredlll08** [comment]
This is an issue with Create. They aren't using the `getRemainingItems` method from `Recipe`, there isn't much I can do to resolve this on my side.
