### ISSUE TITLE
Sqequence Crafting dont load Crafttweaker any more

### ISSUE THREAD

**Issue by SugarDaddii** [jaredlll08/CreateTweaker#25]
After the Update of Create to 0.5.0 Crafttweaker dontload any more with the same recipes for the sequence assemply any more.

https://pastebin.com/98vnF3yT

https://imgur.com/a/hPQu3Ft

**Comment by jaredlll08** [comment]
Fixed by https://github.com/jaredlll08/CreateTweaker/commit/6e4aed04b7e108602136e2f5b12b956eaf942f24
