### ISSUE TITLE
CuttingManager method not found (Not possible to remove craft)

### ISSUE THREAD

**Issue by timo1050** [jaredlll08/CreateTweaker#26]
Add craft : ok.
Remove craft : not ok.

![image](https://user-images.githubusercontent.com/8901731/182245811-752e7ede-bd21-4399-8a8b-d57f85c6d58c.png)
![image](https://user-images.githubusercontent.com/8901731/182245882-27b3c20a-c239-42f1-9254-953ced62592b.png)

I've check the doc and does as expected but don't find if it's come from me or the mod.
(don't put the ";" first time and...)
![image](https://user-images.githubusercontent.com/8901731/182246086-22954d2d-7b1e-451a-a081-24365e544f33.png)

Thx for help or/and answer

**Comment by jaredlll08** [comment]
you need to use `<recipetype:create:cutting>` instead of `CuttingManager`
