### ISSUE TITLE
Some recipe menagers using IItemStack instead IIngredient

### ISSUE THREAD

**Issue by AvallonAB** [jaredlll08/CreateTweaker#27]
Some of the recipe menagers are using IItemStack and IFluidStack instead IIngredient or FluidIngredient, which is quite inconvenient. I'm not sure whether this an issue on the Create side or the CreateTweaker side, however I have noticed that other mods can create recipes, which are impossible to create with CreateTweaker due to aforementioned problem. I don't wish upon my submission to be redundant, so plase just remove it if it is redundant.

**Comment by jaredlll08** [comment]
Can you give examples of which managers you feel are wrong and the type of recipe you would like to add?

**Comment by AvallonAB** [comment]
Well, after further investigation I have come to a conclusion that this issue only applies to recipe menagers, which use fluids as inputs, which means that this should actually br called "Some recipe menagers using IFluidStack instead FluidIngredient". I'm terribly sorry for that error. Examples of recipe menagers which are affected by this are:
- MixingManager
- CompactingManager
- FillingManager
I have noticed it when I was trying to add a mixing recipe, which could use multiple types of fluid as an input. Once again, I'm sorry.

**Comment by jaredlll08** [comment]
So using the Mixing Manager as an example, there are 2 `addRecipe` methods:

```zenscript
// MixingManager.addRecipe(name as string, heat as HeatCondition, outputs as IFluidStack[], itemInputs as IIngredientWithAmount[], fluidInputs as IFluidStack[], duration as int) as void

<recipetype:create:mixing>.addRecipe("fluid_mixed", <constant:create:heat_condition:none>, [<fluid:minecraft:water> * 200], [<item:minecraft:glass> * 2], [<fluid:minecraft:water> * 250], 200);
```
and
```zenscript
// MixingManager.addRecipe(name as string, heat as HeatCondition, outputs as Percentaged<IItemStack>[], itemInputs as IIngredientWithAmount[], fluidInputs as IFluidStack[], duration as int) as void

<recipetype:create:mixing>.addRecipe("mixed", <constant:create:heat_condition:heated>, [<item:minecraft:diamond> % 50, <item:minecraft:apple>, (<item:minecraft:dirt> * 2) % 12], [<item:minecraft:glass> * 2], [<fluid:minecraft:water> * 250], 200);
```

The first one outputs fluids, and the second one outputs items, as for inputs however, you can mix an match items and fluids, like so:
```zenscript
<recipetype:create:mixing>.addRecipe("fluid_mixed", <constant:create:heat_condition:none>, [<fluid:minecraft:water> * 200], [<item:minecraft:glass> * 2], [<fluid:minecraft:water> * 250], 200);
```
That requires 250mb of Water and 2 Glass.

If you just wanted to use the water, you can do:
```zenscript
<recipetype:create:mixing>.addRecipe("fluid_mixed", <constant:create:heat_condition:none>, [<fluid:minecraft:water> * 200], [], [<fluid:minecraft:water> * 250], 200);
```
and if you just wanted to do the glass:
```zenscript
<recipetype:create:mixing>.addRecipe("fluid_mixed", <constant:create:heat_condition:none>, [<fluid:minecraft:water> * 200], [<item:minecraft:glass> * 2], [], 200);
```

So I'm still not following with what type of recipes you can't make.

You mentioned:
> however I have noticed that other mods can create recipes, which are impossible to create with CreateTweaker due to aforementioned problem.

Can you please give me an example of a recipe that is impossible to make with CreateTweaker so I can see how to make it possible.

**Comment by AvallonAB** [comment]
Ok, so I wanted to slightly change certain recipe added by Create Confectionery by removing it and adding it back with the tweak (the tweak doesn't have anything to do with my concerns). This is how the original recipe looks like (generated by /ct recipe command).
`<recipetype:create:mixing>.addRecipe("create_confectionery:gingerdough_recipe", <constant:create:heat_condition:none>, [<item:create_confectionery:gingerdough> % 100.0], [<item:minecraft:sugar>, <item:create:cinder_flour>, <item:create:wheat_flour>], [<fluid:tconstruct:honey> * 250, <fluid:create:honey> * 250], []);`
It accepts 2 differents kinds of honey. Of course if i just removed it and added it back it will requrie both types of honey at the same time and not just one of them and using a tag doesn't work since the recipe menager requires IFluidStack as input. I just want to say that it is currently impossible to have a recipe, which accepts several types of fluids. Sorry for not being clear before.

**Comment by AvallonAB** [comment]
@jaredlll08 Hi, sorry for interrupting you, however I have started worrying you might have forgotten, but it's probably you just being bussy. I don't want to distract you, so if you don't have time just ignore this message.

**Comment by jaredlll08** [comment]
I can confirm that this recipe:
```
<recipetype:create:mixing>.addRecipe("gingerdough_recipe", <constant:create:heat_condition:none>, [<item:minecraft:diamond> % 100.0], [<item:minecraft:sugar>, <item:create:cinder_flour>,<item:create:wheat_flour>], [<tag:fluids:forge:honey> * 250], 200);
```
works as you intended, all I did was replace the fluids with the tag, and the output with a diamond because I don't have that other mod installed.
```
