### ISSUE TITLE
Fabric Support?

### ISSUE THREAD

**Issue by Imoriarty** [jaredlll08/CreateTweaker#29]
I recently switched over to Fabric from Forge to give it a try, and while Create works fine, this integration doesn't seem to support my existing Teaks on the Fabric side. Is there not support for Fabric, or is there something I've missed?

**Comment by skiller8641** [comment]
does the mod even have a fabric version, in the curseforge page it doesn't have the fabric tag

**Comment by jaredlll08** [comment]
There is a fabric version, it is not an official port (at-least in the sense of being on the same curseforge page), but it does exist

**Comment by ChromeTV** [comment]
can someone put the fabric port mod page? i cant found it :p

**Comment by jaredlll08** [comment]
https://www.curseforge.com/minecraft/mc-mods/create-fabric

**Comment by ChromeTV** [comment]
thx

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/CreateTweaker/commit/28edf9a71ccf421806a57a50fea868f30e4c4144.
1.20.1 and above only.
