### ISSUE TITLE
Broken by Create 0.5.1b

### ISSUE THREAD

**Issue by nyxatledgerocks** [jaredlll08/CreateTweaker#31]
![image](https://github.com/jaredlll08/CreateTweaker/assets/134436513/3ec0aa71-413a-4e7d-b204-d9afef3fdd26)
Using CreateTweaker's standard documentation procedure for crafting, doesn't work.

**Comment by jaredlll08** [comment]
I need:
The Script
MC version 
CreateTweaker version

Please

**Comment by nyxatledgerocks** [comment]
I deleted the script, unfortunately, but it was mixing eight blackstone and a gold ingot into a gilded blackstone.
MC version is 1.19.2
CreateTweaker version is latest as of this morning

**Comment by nyxatledgerocks** [comment]
Apologies I couldn't be more helpful

**Comment by jaredlll08** [comment]
I just updated my dev environment to 0.5.1b and all the scripts are working fine.

Without your script I can't help you unfortunately, but I can confirm that nothing is broken with the mod.

**Comment by nyxatledgerocks** [comment]
Update: retried this with a new script

import mods.createtweaker.MixingRecipe;
import mods.create.MixingManager;
import mods.create.IProcessingRecipeManager;
MixingManager.addJsonRecipe("mixed_gilded_blackstone", \<item:minecraft:gilded_blackstone\>, [\<item:minecraft:blackstone\>, \<item:minecraft:gold_nugget\>]);
![image](https://github.com/jaredlll08/CreateTweaker/assets/134436513/c9572d71-f168-499d-8432-bd526f4e9e9b)

**Comment by nyxatledgerocks** [comment]
Updated update: tried with another type, and it just straight up didn't work even though it didn't throw an error

import mods.createtweaker.ItemApplicationRecipe;
import mods.create.ItemApplicationManager;
import mods.create.IProcessingRecipeManager;
\<recipetype:create:item_application\>.addRecipe("applied_gilded_blackstone", [\<item:minecraft:gilded_blackstone\> % 100], \<item:minecraft:blackstone\>, \<item:minecraft:gold_nugget\>, false);

**Comment by jaredlll08** [comment]
Using your script verbatim I can confirm that it works.
![image](https://github.com/jaredlll08/CreateTweaker/assets/5553605/93858a52-2484-4f2c-84d3-2b890462a4ba)

**Comment by nyxatledgerocks** [comment]
H u h. Okay, thank you, it's something weird with my setup then. Thank you for your help!
