### ISSUE TITLE
[1.20.1] Error durring launch

### ISSUE THREAD

**Issue by ghost** [jaredlll08/CreateTweaker#34]
Forge version : 47.1.47
CraftTweaker version : 14.0.16
Create version : 0.5.1d
CreateTweaker version : 4.0.5

Works perfectly fine without it.

Get a crash during launch : 

Here the log -> https://pastebin.com/6U5iEY2z

**Comment by kreezxil** [comment]
same here.

crash report: https://gist.github.com/kreezxil/76e763b5a0b683db91eb68c70d194854
crafttweaker log: https://paste.centos.org/view/3c05c633
latest log: https://paste.centos.org/view/1f1a3a80

Forge: 47.1.47
Craftteaker: 14.0.16
createtewaker: 4.0.5
create: 0.5.1d

mods: https://paste.centos.org/view/fd8ded56

dirt screen error:
![image](https://github.com/jaredlll08/CreateTweaker/assets/3880072/d7de78dc-1947-488d-a120-ebf1fd95faf5)

**Comment by ghost** [comment]
Seems related to this → https://github.com/jaredlll08/CreateTweaker/blob/4a380a0e95c1eab4fc59d2ba07bfb73adbb5e279/forge/src/main/java/com/blamejared/createtweaker/natives/recipe/ExpandSplashingRecipe.java#L6

Will try to fix it by myself

**Comment by jaredlll08** [comment]
Update to Create 0.5.1.e and it will work, seems I was working on that version instead of `d`, I have since bumped the required version up.
