### ISSUE TITLE
Resultant Recipe item is wrong

### ISSUE THREAD

**Issue by RedBlockCreator** [jaredlll08/CreateTweaker#4]
<recipetype:create:mechanical_crafting>.addRecipe("mechanical_crafter_test", <item:minecraft:diamond>, [[<item:minecraft:stick>, <item:minecraft:air>, <item:minecraft:stick>], [<item:minecraft:air>, <item:minecraft:stick>, <item:minecraft:air>]]);

This is the example script given on the craft tweaker wiki for this mod, however when the items are input and the crafting operation goes through, it outputs the wrong item. In this case, xreliquary:magazines/neutral_magazine
which is weird because diamond is what JEI sees it is supposed to put out, but it does not.

**Comment by jaredlll08** [comment]
Firstly please put scripts on pastebin or in ```code blocks```
Secondly, this is either an issue where you have a conflicting recipe or an issue with Create.

If you see it in JEI, it means that the recipe was added fine, and the issue is something else.
