### ISSUE TITLE
Can 1.19.2 fabric support be added?

### ISSUE THREAD

**Issue by Monke-Lord** [jaredlll08/CreateTweaker#41]
I am playing on a 1.19.2 modded server and we have want to tweak some recipes to make them less of a grind to get. 
So if you have time please add 1.19.2 fabric support.

**Comment by jaredlll08** [comment]
I will not be adding fabric support for any older versions. 

This page should help you add recipes https://docs.blamejared.com/1.19/en/mods/other_mods
