### ISSUE TITLE
[1.18.2] Chances not working for create:sandpaper_polishing

### ISSUE THREAD

**Issue by Crimssoon** [jaredlll08/CreateTweaker#43]
`<recipetype:create:sandpaper_polishing>.addRecipe("scratch_card_results", <item:city_modernities:dollars_bag> % 25, <item:lottery:lottery>, 200);`

Instead of erroring, it gives the recipe 100 % everytime.
item:lottery:lottery might sound wrong but it's right, I just named the mod weirdly.

**Comment by jaredlll08** [comment]
Sandpaper polishing does not support chances, all of create's json recipes *can* accept a chanced input however, which is why it accepts it in the script, even though it doesn't work.
