### ISSUE TITLE
Extension and compatibility issues

### ISSUE THREAD

**Issue by semenishchev** [jaredlll08/CreateTweaker#44]
Some Create addons require their own CraftTweaker addons. For example Destroy. It has its own FluidIngredient class, which is required for its recipes to work. I was thinking of extending the CTFluidIngredient, but its constructor is package-private. 

Mixin would help, but the only way of attaching a mixin would be a static jar dependency, so it'd be nice to have CreateTweaker uploaded to a repository

**Comment by jaredlll08** [comment]
> Mixin would help, but the only way of attaching a mixin would be a static jar dependency, so it'd be nice to have CreateTweaker uploaded to a repository

CreateTweaker is already hosted on my maven https://maven.blamejared.com/com/blamejared/createtweaker/
