### ISSUE TITLE
Incompatibility with Create Fabric 0.5.1f

### ISSUE THREAD

**Issue by JensenJ** [jaredlll08/CreateTweaker#45]
Create Fabric updated today to version 0.5.1f and this has a large number of changes which affect this mod and recipe creation. I think the main change is to do with fan processing recipes as they added support for custom fan processing types.

Log: [crash-2024-03-09_21.07.31-client.txt](https://github.com/jaredlll08/CreateTweaker/files/14547824/crash-2024-03-09_21.07.31-client.txt)
I'm aware other mods are in this crash report but they work without CreateTweaker installed and it did work before the Create update.

**Comment by Technique35** [comment]
Getting this same crash as well, even with bare minimum mods (CreateTweaker, CraftTweaker, Create, FabricAPI, FauxCustomEntityData)
