### ISSUE TITLE
Missing recipeType for bulk blasting/smoking/washing

### ISSUE THREAD

**Issue by Patrick15a** [jaredlll08/CreateTweaker#5]
Hello, is there a way to add recipes for blasting, smoking or washing?

I can't find any documentation ore about that and no code in the source code for that.

With best regards,
Patrick15a

----------
Minecraft Version: 1.16.4
Create Version: 0.3e
CreateTweaker Version: 1.0.0.9
CraftTweaker Version: 7.1.0.184

**Comment by jaredlll08** [comment]
Blasting and Smoking use the vanilla registry for their recipes (so using `blasting` or `smoking` will add the recipe to those machines).


Washing I think is the Splashing recipe 
Splashing I think is the

**Comment by Patrick15a** [comment]
Thanks for the quick answer and clarification. 👍
