### ISSUE TITLE
Generated Filling recipes cannot be removed

### ISSUE THREAD

**Issue by Hedgehog0091** [jaredlll08/CreateTweaker#6]
I'm using Minecraft 1.16.5, Forge 36.1.4, CraftTweaker 1.16.5-7.1.0.216, Create 1.16.4+ 0.3.1c, and CreateTweaker 1.0.0.11 (and some others like JEI, but nothing that should affect this).
Short version: read the title.
Long version: It seems that Create generates recipes such as filling bottles with potion and buckets with fluid, alongside some recipes added via datapacks. These manually added recipes (such as `create:filling/blaze_cake`) can be removed with the IRecipeManager functions. However, generated recipes (such as `create:fill_minecraft_bucket_with_create_honey`) cannot. If I try to add `<recipetype:create:filling>.removeByName("create:fill_minecraft_bucket_with_create_honey");` to a script, CrafttTweaker complains it cannot find any recipe with such a name, even though JEI shows it exists and it can be crafted.

**Comment by DaRealSparky** [comment]
I am having a similar issue on 1.18.2. However, it seems to be spread across multiple different crafting managers, including the crushing wheels.

**Comment by jaredlll08** [comment]
There is nothing that can be done about this.

The recipes you are seeing in JEI are fake recipes, they don't actually exist, Create is just creating recipes for all generic fluid containers (bucket for example) to be filled with all the different types of fluids.

The actual interaction of filling the containers isn't a recipe that can be removed and is hard coded in Create itself.
