### ISSUE TITLE
Mixing: removeRecipe(< Any fluid: not working

### ISSUE THREAD

**Issue by 4inchezz** [jaredlll08/CreateTweaker#8]
It seems that this isnt working anymore:
<recipetype:create:mixing>.removeRecipe(<fluid:create:tea>);

The script is taken directly from https://docs.blamejared.com/1.16/de/mods/Create/Mixing/

Ingame it says Parameter 0: cannot cast IFluidStack to IItemStack
I guess it doesnt recognize Fluids as an recipe output anymore. This script used to work on older versions tho

**Comment by jaredlll08** [comment]
full script and log (/ct log) on pastebin please.

**Comment by jaredlll08** [comment]
Fixed on discord, was using an old createtweaker
