### ISSUE TITLE
Making a recipe using two fluids in a mixer beraks things very badly

### ISSUE THREAD

**Issue by TacocaTYT** [jaredlll08/CreateTweaker#9]
I attempted to make this recipe
`<recipeType:create:mixing>.addRecipe("icing_mixing", "heated", <fluid:contenttweaker:icing> * 20, [<tag:items:forge:crops/vanillabean> * 2], [<fluid:contenttweaker:molten_sugar> * 20, <fluid:minecraft:milk> * 20], 20);`
Using a cusotm fluid and milk and vanilla beans to make a custom fluid called icing. this does not work no mixing occurs despite a recipe appearing in JEI
I changed the recipe to only use the molten sugar custom fluid, then proceeded with the following tests.
I added the recipe 
`<recipeType:create:mixing>.addRecipe("test_one", "none", <item:minecraft:diamond>, [<item:minecraft:air>], [<fluid:minecraft:lava>, <fluid:minecraft:water>]);`
to test if it was an issue with two fluid recipes, which it wasn't as this made 1mb lava and 1mb water into 1 diamond.
next I attempted 
`<recipeType:create:mixing>.addRecipe("test_one", "none", <item:minecraft:diamond>, [<item:minecraft:dirt>], [<fluid:minecraft:lava>, <fluid:minecraft:water>]);`
and this too worked, and made lava, water, and dirt into a diamond.

so then I re-added the second fluid to the original recipe and it instantly broke itself  resulting in no mixing occurring.

**Comment by jaredlll08** [comment]
Please upload your `crafttweaker.log` file to pastebin. (`/ct log`)

**Comment by TacocaTYT** [comment]
https://pastebin.com/4HDkgAPP

**Comment by TacocaTYT** [comment]
like this?

**Comment by jaredlll08** [comment]
So I'm unable to reproduce,

I used the following script as I don't have those items / fluids in my game:

```zenscript
<recipeType:create:mixing>.addRecipe("icing_mixing", "heated", <fluid:minecraft:lava>, [<item:minecraft:white_wool> * 2], [<fluid:create:honey> * 20, <fluid:minecraft:water> * 20], 20);
```

Something to keep in mind, you set the recipe to "heated" meaning that it needs to have a blaze burner beneath it *and* that blaze burner needs to have fuel (that confused me for a while).

**Comment by TacocaTYT** [comment]
i have the heating set up properly, and  in this case maybe ist an issue with content tweaker fluids?

**Comment by jaredlll08** [comment]
It shouldn't be an issue with the contenttweaker fluid, is your script (the one adding the recipe).

Did you try my script to see if that one works?

**Comment by TacocaTYT** [comment]
i did not try your specific script no, but when i used my script using water and lava it worked normally

**Comment by jaredlll08** [comment]
Yes but if you look, my script outputs a fluid, like your original one does, your other scripts don't. That is why I am saying try my script sin e it could be treating things differently

**Comment by TacocaTYT** [comment]
oh good point, i'll try that when i get home

**Comment by jaredlll08** [comment]
And replacing the water in my script with a contenttweaker fluid? Does that work?

**Comment by TacocaTYT** [comment]
that breaks it again

**Comment by jaredlll08** [comment]
Then report it to Content Tweaker, since something with those fluids must be messed

**Comment by TacocaTYT** [comment]
done
